Update extensions.json
Kentico/devnet.kentico.com pull request #105
Opened 2020-08-21 07:37 UTC by dilip-sipl

Page categories widget can be added as an inline widget in editable region or in widget zone, and will display categories of current page with specified separator and design styling which can be configured in widget properties.

2020-08-27 09:39 UTC, dilip-sipl commented
> Could you pease adjust the description length? It must be less than or equal to 160 characters long. Thank you!

Hello, I have made the changes. Can you please review and do the needful to merge the changes? 
Thanks

2020-08-30 08:22 UTC, giorgioLUK approved these changes

2020-08-30 08:29 UTC, giorgioLUK requested changes
@dilip-sipl, "category" must be one of [module, webpart, website template, utility, mvc widget, mvc section, mvc form component, mvc inline editor, mvc personalization condition type, integration, other]], could you please adjust it? Thanks!

2020-09-11 10:37 UTC, dilip-sipl commented
> @dilip-sipl, "category" must be one of [module, webpart, website template, utility, mvc widget, mvc section, mvc form component, mvc inline editor, mvc personalization condition type, integration, other]], could you please adjust it? Thanks!

I have updated the category.

May I request, can you please review and let me know your feedback?

Thanks

2020-09-11 11:54 UTC, giorgioLUK approved these changes

2020-09-11 11:58 UTC, merged